"""create table subject and user_subject_assosiation

Revision ID: 6731e3b89336
Revises: 4206985b6bee
Create Date: 2023-12-23 13:23:12.271026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6731e3b89336'
down_revision: Union[str, None] = '4206985b6bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('name', sa.String(), nullable=False),
    sa.CheckConstraint("name IN ('mathematics', 'informatics', 'programming')", name='name'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('subject_user_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_name'], ['subject.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subject_name', name='idx_unique_user_subject')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_user_association')
    op.drop_table('subject')
    # ### end Alembic commands ###
