"""delete UniqueConstraint name=idx_unique_user_subject_order

Revision ID: 5dbd9a9ff316
Revises: efdf75f8f104
Create Date: 2024-02-04 16:19:53.659443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbd9a9ff316'
down_revision: Union[str, None] = 'efdf75f8f104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_unique_user_subject_order', 'order', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_unique_user_subject_order', 'order', ['user_id', 'subject_name'])
    # ### end Alembic commands ###
