"""create table Subject

Revision ID: 6985982cc300
Revises: fce6fc94dde2
Create Date: 2024-02-04 16:56:29.957533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6985982cc300'
down_revision: Union[str, None] = 'fce6fc94dde2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('name', sa.String(), nullable=False),
    sa.CheckConstraint("name IN ('mathematics', 'informatics', 'programming')", name='name'),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject')
    # ### end Alembic commands ###
